defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: cms
  password: cms
  host: localhost
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>

development:
  database: cms_dev
  <<: *defaults

test:
  database: cms_test
  <<: *defaults

production: &deploy
  <<: *defaults

staging: *deploy
